<?php

/**
 * Generated By GZeinNumerCodeGenerator
 * www.github.com/gzeinnumer
 * at 2022-07-09 18:29:14
 * zip name 20220709182914_products_DdLg69vR18.zip
 */

namespace App\Http\Controllers\API;

use App\Http\Resources\ProductsResources;
use App\Models\API\ProductsModel;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Validator;

class ProductsController extends BaseController
{
    /*
    {
        "name" : "",
        "flag_active" : ""
    }
    */
    //localhost:8000/api/products/insert
    public function insert(Request $r)
    {
        try {
            //to validate duplicate data
            //change activeValidateDuplicateData to true, if you want to validate 
            //if mobile sent duplicate data 
            //add "created_at" : "2022-08-04 16:08:09" to json
            /*
            {
                "object1" : "data 1",
                "object2" : "data 2",
                "created_at" : "2022-08-04 16:08:09" // current time
            }
            */

            $activeValidateDuplicateData = false;
            if ($activeValidateDuplicateData) {
                $data = ProductsModel::where([
                    "name" => $r->name,
                    "flag_active" => $r->flag_active,
                    "created_at" => $r->created_at,
                ])->first();
                if ($data != null) {
                    $apiResponse = $this->getApiResponse(1);
                    return $this->responseSuccess($apiResponse);
                }
            }

            $input = array(
                'name' => 'required|string|min:1',
                'flag_active' => 'required|string|min:1',
            );

            $validator = Validator::make($r->all(), $input);

            if ($validator->fails()) {
                $apiResponse = $this->getApiResponse(0);
                $apiResponse->message = $validator->getMessageBag();
                return $this->responseFailed($apiResponse);
            }

            DB::beginTransaction();

            $data = new ProductsModel();
            $data->name = $r->name;
            $data->flag_active = $r->flag_active;
            $data->save();

            DB::commit();

            $apiResponse = $this->getApiResponse(1);
            return $this->responseSuccess($apiResponse);
        } catch (\Throwable $th) {
            DB::rollBack();
            return $this->responseError($th);
        }
    }

    //localhost:8000/api/products/all
    public function all()
    {
        try {
            $data = ProductsModel::all();

            return $this->toList(ProductsResources::collection($data), 1, 0);
        } catch (\Throwable $th) {
            return $this->responseError($th);
        }
    }

    //http://localhost:8000/api/products/paging?limit=10&page=1&start_date=2023-01-01&end_date=2023-01-01
    public function paging(Request $r)
    {
        try {
            $limit = $r->limit ? $r->limit : 10;
            $page = $r->page ? $r->page : 1;
            $start_date = $r->start_date;
            $end_date = $r->end_date;

            $query = DB::table('products');

            if ($start_date) {
                $query = $query->wherebetween("products.created_at", array($start_date . " 00:00:00", $end_date . " 23:59:59"));
            }

            $dataParsing = $query;

            return $this->toPaging(
                1,
                $dataParsing,
                $limit,
                $page
            );
        } catch (\Throwable $th) {
            return $this->responseError($th);
        }
    }

    /*
    {
        "name" : "",
        "flag_active" : ""
    }
    */
    //localhost:8000/api/products/update/1
    public function update(Request $r, $id)
    {
        try {
            $input = array(
                'name' => 'required|string|min:1',
                'flag_active' => 'required|string|min:1',
            );

            $validator = Validator::make($r->all(), $input);

            if ($validator->fails()) {
                $apiResponse = $this->getApiResponse(0);
                $apiResponse->message = $validator->getMessageBag();
                return $this->responseFailed($apiResponse);
            }

            DB::beginTransaction();

            $data = ProductsModel::find($id);
            $data->name = $r->name;
            $data->flag_active = $r->flag_active;
            $data->save();

            DB::commit();

            $apiResponse = $this->getApiResponse(1);
            return $this->responseSuccess($apiResponse);
        } catch (\Throwable $th) {
            DB::rollBack();
            return $this->responseError($th);
        }
    }

    //localhost:8000/api/products/delete/1
    public function delete($id)
    {
        try {
            $data = ProductsModel::find($id);

            DB::beginTransaction();

            $data->delete();

            DB::commit();

            $apiResponse = $this->getApiResponse(1);
            return $this->responseSuccess($apiResponse);
        } catch (\Throwable $th) {
            return $this->responseError($th);
        }
    }

    //localhost:8000/api/products/find/1
    public function find($id)
    {
        try {
            $data = ProductsModel::find($id);

            return $this->toObject(new ProductsResources($data), 1, 0);
        } catch (\Throwable $th) {
            return $this->responseError($th);
        }
    }
}
